language: node_js
node_js:
  - "node"
  - "9"

before_install: cd project
install:
  - yarn install
  - cd client && yarn install

before_script: cd project
script:
  - yarn test
  - cd client && yarn build && yarn test

git:
  depth: 10
  submodules: false

# Whitelist master branch
branches:
  only: 
    - master

