language: node_js
node_js:
  - "node"
  - "9"

install:
  - yarn install
  - cd client
  - yarn install
  - cd ..

script:
  - yarn test
  - cd client
  - yarn build
  - yarn test
  - cd ..

git:
  depth: 10
  submodules: false

# Whitelist master branch
branches:
  only: 
    - master

